---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-conf-pvc
  namespace: openhab
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-conf-repo-pvc
  namespace: openhab
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-userdata-pvc
  namespace: openhab
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10M
