---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openhab-config
  namespace: openhab
data:
  config.yaml: |
    groups:
      house:
        name: House
      floor_ground:
        name: Floor_Ground
      floor_first:
        name: Floor_First
      floor_second:
        name: Floor_Second
      room_bedroom_main:
        name: Room_Bedroom_main
    things:
      airquality:
        station_id: 86
        # station_id: 110863
      daikin_great_room:
        host: great-room.hvac.home.lan
        thing_id: great_room
      daikin_main_bedroom:
        host: main-bedroom.hvac.home.lan
        thing_id: main_bedroom
      zwave_controller:
        port: /dev/ttyUSB0
    settings:
      addons:
        package: minimal
        binding: airquality,bluetooth,daikin,network,systeminfo,telegram,zwave
        persistence: influxdb
        ui: basic,habmin,paper,restdocs
      ephemeris:
        country: us
        region: or
        dayset:
          trash: Friday
      influxdb:
        db: openhab
        url: http://influxdb:8086
      i18n:
        language: en
        region: US
        timezone: US/Pacific
        measurement_system: US
