---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: openhab
  namespace: openhab
  annotations:
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: openhab-basic-auth
spec:
  rules:
  - host: openhab.home.lan
    http:
      paths:
      - path: /
        backend:
          serviceName: openhab
          servicePort: 80
