---
groups:
  house:
    name: null
  floor_ground:
    name: null
  floor_first:
    name: null
  floor_second:
    name: null
  room_bedroom_main:
    name: null
things:
  airquality:
    station_id: null
  daikin:
    great_room:
      host: null
      label: null
      location: null
      thing_id: null
      type_id: null
    main_bedroom:
      host: null
      label: null
      location: null
      thing_id: null
      type_id: null
  zwave:
    controller:
      port: null
    sensors:
      front_door:
        label: null
        location: null
        node_id: null
        thing_id: null
        type_id: null
      garage_door:
        label: null
        location: null
        node_id: null
        thing_id: null
        type_id: null
settings:
  addons:
    action: null
    package: null
    binding: null
    persistence: null
    transformation: null
    ui: null
  ephemeris:
    country: null
    region: null
    dayset:
      trash: null
  persistence:
    influxdb:
      db: null
      url: null
  i18n:
    language: null
    region: null
    timezone: null
    measurement_system: null
