---
settings:
  addons:
    package: minimal
    binding: airquality,bluetooth,daikin,systeminfo,telegram,zwave
    persistence: influxdb
    ui: basic,habmin,paper,restdocs
  ephemeris:
    country: us
    region: or
    dayset:
      trash: Friday
  i18n:
    language: en
    region: US
    timezone: US/Pacific
    measurement_system: US

groups:
  house:
    name: House
  floor_ground:
    name: Floor_Ground
  floor_first:
    name: Floor_First
  floor_second:
    name: Floor_Second
  room_bedroom_main:
    name: Room_Bedroom_main
things:
  airquality:
    station_id: 86
  daikin_great_room:
    thing_id: great_room
  daikin_main_bedroom:
    thing_id: main_bedroom
  zwave_great_room:
    port: /dev/ttyUSB0
    thing_id: controller
