home_coordinates: null

things:
  airquality:
    apikey: null
  networking:
    james_modile:
      hostname: null
      mac_address: null
      thing_id: null
      type_id: null
  telegram:
    chat_id: null
    token: null
  zwave:
    controller:
      security_network_key: null
