home_coordinates: null

settings:
  persistence:
    influxdb:
      user: null
      password: null
  telegram:
    bot1:
      chat_id: null
      token: null

things:
  airquality:
    apikey: null
  networking:
    mobile_phone:
      hostname: null
      items:
      - name: null
        type: null
        channel: null
      - name: null
        type: null
        channel: null
      - name: null
        type: null
        channel: null
      mac_address: null
      name: null
      thing_id: null
      type_id: null
  telegram:
    chat_id: null
    token: null
  zwave:
    controller:
      security_network_key: null
