home_coordinates: null

things:
  airquality:
    apikey: null
  networking:
    james_mobile:
      hostname: null
      items:
      - name: null
        type: null
        channel: null
      - name: null
        type: null
        channel: null
      - name: null
        type: null
        channel: null
      mac_address: null
      name: null
      thing_id: null
      type_id: null
  telegram:
    chat_id: null
    token: null
  zwave:
    controller:
      security_network_key: null
