home_coordinates: null

things:
  airquality:
    apikey: null
  daikin_great_room:
    host: null
  daikin_main_bedroom:
    host: null
  telegram:
    chat_id: null
    token: null
  zwave_great_room:
    security_network_key: null
